version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "CI/CD"
      - "dependabot"
    commit-message:
      prefix: ci
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        patterns:
          - "*"
