---
secrets:
  COPILOT_API_URL:
    key: COPILOT_API_URL
    type: config
    owner: "@github/customer-success-engineering"
    playbook:
    externally_usable: false
    kind: latest_at_deployment_start
  CSE_COPILOT_HMAC_KEY:
    key: CSE_COPILOT_HMAC_KEY
    type: HMAC
    owner: "@github/customer-success-engineering"
    playbook: https://github.com/github/trust-metadata-api/blob/main/docs/playbooks/rotate-hmac-keys.md
    externally_usable: true
    kind: latest_at_deployment_start
  CSE_COPILOT_SERVICE_URL:
    key: CSE_COPILOT_SERVICE_URL
    type: config
    owner: "@github/customer-success-engineering"
    playbook:
    externally_usable: false
    kind: latest_at_deployment_start
  kittens:
    key: kittens
    type: kittens
    owner: ''
    playbook:
    externally_usable: false
    kind: latest_at_deployment_start
